version: 2

project_name: kairos-must-burn
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=1
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - -w -s -H=windowsgui
    binary: '{{ .ProjectName }}'
    id: build-windows
  - env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -w -s
    binary: '{{ .ProjectName }}'
    id: build-linux
  - env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - arm64
    ldflags:
      - -w -s
    binary: '{{ .ProjectName }}'
    # TODO: after build, it should copy the binary into the kairos-must-burn.app dir to have a proper macos app
    id: build-darwin